apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
  name: cloudcore
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      k8s-app: kubeedge
      kubeedge: cloudcore
  template:
    metadata:
      labels:
        k8s-app: kubeedge
        kubeedge: cloudcore
    spec:
      hostNetwork: true
      containers:
      - name: cloudcore
        image: kubeedge/cloudcore:v1.4.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.cloudhub.websocket.port }}
          name: wss
          protocol: TCP
        - containerPort: {{ .Values.cloudhub.https.port }}
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - name: conf
          mountPath: /etc/kubeedge/config
        - name: certs
          mountPath: /etc/kubeedge
      restartPolicy: Always
      serviceAccount: cloudcore
      serviceAccountName: cloudcore
      volumes:
      - name: conf
        configMap:
          name: cloudcore
      - name: certs
        hostPath:
          path: /etc/kubeedge
          type: DirectoryOrCreate
