apiVersion: v1
kind: Service
metadata:
  name: cloudcore
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
spec:
  ports:
  - port: {{ .Values.cloudHub.https.port }}
    nodePort: 30002
    name: https
  - port: {{ .Values.cloudHub.websocket.port }}
    nodePort: 30000
    name: wss
  selector:
    k8s-app: kubeedge
    kubeedge: cloudcore
  type: {{ .Values.service.type }} 
