apiVersion: v1
kind: Service
metadata:
  name: cloudcore
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: cloudhub
  selector:
    k8s-app: kubeedge
    kubeedge: cloudcore
  type: {{ .Values.service.type }} 
