apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: green-led
  labels:
    description: LEDLight
    model: led
spec:
  deviceModelRef:
    name: led
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: ''
        operator: In
        values:
        - raspberry 
status:
  twins:
    - propertyName: power-status
      desired:
        metadata:
          type: string
        value: 'OFF'
